name: Publish storybook to ghpages
on:
  push:
    branches:
      - "main"
jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}      
      - run: npm ci
      - name: Deploy storybook to GitHub Pages
        run: npm run deploy-storybook -- --ci --host-token-env-variable=GH_TOKEN
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}      