name: Publish storybook to ghpages
on:
  push:
    branches:
      - "main"
jobs:
  publish-storybook:
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      GH_USER: ${{secrets.GH_USER}}
      GH_EMAIL: ${{secrets.GH_EMAIL}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}      

      - name: 'setup git coordinates'
        run: |
          git remote set-url origin https://veramolabs:$GH_TOKEN@github.com/veramolabs/agent-explorer.git
          git config user.name $GH_USER
          git config user.email $GH_EMAIL

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static # output folder from `npm run build-storybook`